name: Comment on Issue Close

on:
  issues:
    types: [closed]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on Closed Issue
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Thank you for your contribution! If you have any questions or need further assistance, feel free to reach out to us on our Discord server: [Discord](https://discord.gg/rZb46cCMmK). We have separate channels for all projects. Happy coding! ğŸš€ \n\n Don't forget to connect with us for open source updates\n âœ”ï¸[LinkedIn](https://www.linkedin.com/company/chromegaming) \n âœ”ï¸[GitHub](https://github.com/GameSphere-MultiPlayer) \n âœ”ï¸[Instagram](https://www.instagram.com/chromegamingon/) '
            });
            console.log(response);
